// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medical.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Medical {
  public static partial class DoctorResultsGetter
  {
    static readonly string __ServiceName = "medical.DoctorResultsGetter";

    static readonly grpc::Marshaller<global::Medical.FilterRequest> __Marshaller_FilterRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.FilterRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Medical.MedicalData> __Marshaller_MedicalData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.MedicalData.Parser.ParseFrom);

    static readonly grpc::Method<global::Medical.FilterRequest, global::Medical.MedicalData> __Method_GetResults = new grpc::Method<global::Medical.FilterRequest, global::Medical.MedicalData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetResults",
        __Marshaller_FilterRequest,
        __Marshaller_MedicalData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Medical.MedicalReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DoctorResultsGetter</summary>
    public abstract partial class DoctorResultsGetterBase
    {
      public virtual global::System.Threading.Tasks.Task GetResults(global::Medical.FilterRequest request, grpc::IServerStreamWriter<global::Medical.MedicalData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DoctorResultsGetter</summary>
    public partial class DoctorResultsGetterClient : grpc::ClientBase<DoctorResultsGetterClient>
    {
      /// <summary>Creates a new client for DoctorResultsGetter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DoctorResultsGetterClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DoctorResultsGetter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DoctorResultsGetterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DoctorResultsGetterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DoctorResultsGetterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Medical.MedicalData> GetResults(global::Medical.FilterRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetResults(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Medical.MedicalData> GetResults(global::Medical.FilterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetResults, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DoctorResultsGetterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DoctorResultsGetterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DoctorResultsGetterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetResults, serviceImpl.GetResults).Build();
    }

  }
  public static partial class TechnicianResultsAdder
  {
    static readonly string __ServiceName = "medical.TechnicianResultsAdder";

    static readonly grpc::Marshaller<global::Medical.MedicalData> __Marshaller_MedicalData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.MedicalData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Medical.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Medical.MedicalData, global::Medical.Empty> __Method_AddNewResult = new grpc::Method<global::Medical.MedicalData, global::Medical.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddNewResult",
        __Marshaller_MedicalData,
        __Marshaller_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Medical.MedicalReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of TechnicianResultsAdder</summary>
    public abstract partial class TechnicianResultsAdderBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Medical.Empty> AddNewResult(global::Medical.MedicalData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TechnicianResultsAdder</summary>
    public partial class TechnicianResultsAdderClient : grpc::ClientBase<TechnicianResultsAdderClient>
    {
      /// <summary>Creates a new client for TechnicianResultsAdder</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TechnicianResultsAdderClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TechnicianResultsAdder that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TechnicianResultsAdderClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TechnicianResultsAdderClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TechnicianResultsAdderClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Medical.Empty AddNewResult(global::Medical.MedicalData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddNewResult(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Medical.Empty AddNewResult(global::Medical.MedicalData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddNewResult, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Medical.Empty> AddNewResultAsync(global::Medical.MedicalData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddNewResultAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Medical.Empty> AddNewResultAsync(global::Medical.MedicalData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddNewResult, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TechnicianResultsAdderClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TechnicianResultsAdderClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TechnicianResultsAdderBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddNewResult, serviceImpl.AddNewResult).Build();
    }

  }
  public static partial class PatientResultsGetter
  {
    static readonly string __ServiceName = "medical.PatientResultsGetter";

    static readonly grpc::Marshaller<global::Medical.PatientRequest> __Marshaller_PatientRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.PatientRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Medical.MedicalData> __Marshaller_MedicalData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Medical.MedicalData.Parser.ParseFrom);

    static readonly grpc::Method<global::Medical.PatientRequest, global::Medical.MedicalData> __Method_GetResults = new grpc::Method<global::Medical.PatientRequest, global::Medical.MedicalData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetResults",
        __Marshaller_PatientRequest,
        __Marshaller_MedicalData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Medical.MedicalReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of PatientResultsGetter</summary>
    public abstract partial class PatientResultsGetterBase
    {
      public virtual global::System.Threading.Tasks.Task GetResults(global::Medical.PatientRequest request, grpc::IServerStreamWriter<global::Medical.MedicalData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PatientResultsGetter</summary>
    public partial class PatientResultsGetterClient : grpc::ClientBase<PatientResultsGetterClient>
    {
      /// <summary>Creates a new client for PatientResultsGetter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PatientResultsGetterClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PatientResultsGetter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PatientResultsGetterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PatientResultsGetterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PatientResultsGetterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Medical.MedicalData> GetResults(global::Medical.PatientRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetResults(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Medical.MedicalData> GetResults(global::Medical.PatientRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetResults, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PatientResultsGetterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PatientResultsGetterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PatientResultsGetterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetResults, serviceImpl.GetResults).Build();
    }

  }
}
#endregion
